# Build Stage
FROM node:22-slim as builder

WORKDIR /app
COPY package*.json ./
RUN npm ci

COPY . .

# Increase memory limit for node to prevent OOM
ENV NODE_OPTIONS="--max-old-space-size=4096"
RUN npm run build

# Production Stage
FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
