version: '3.8'

services:
  # Frontend (Nginx)
  ops-navigation:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - api
    environment:
      - API_URL=http://api:3001
    networks:
      - ops-net

  # Backend API
  api:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      # Connect to the mongo service using the container name
      - MONGODB_URI=mongodb://mongo:27017/opsbridge
      - PORT=3001
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - ops-net

  # MongoDB
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      # Mount the Chinese initialization script
      - ./init-mongo-zh.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      # This triggers the initialization script if the DB is empty
      - MONGO_INITDB_DATABASE=opsbridge
    restart: unless-stopped
    networks:
      - ops-net

volumes:
  mongo_data:

networks:
  ops-net:
    driver: bridge
